"""Regression tests for the cross-platform Zingg contract capsule canonicalizer."""
from __future__ import annotations

import hashlib
import importlib.util
import tempfile
import unittest
import zipfile
from pathlib import Path


SCRIPT = Path(__file__).resolve().parents[1] / "normalize-zingg07-jar.py"
SPEC = importlib.util.spec_from_file_location("normalize_zingg07_jar", SCRIPT)
assert SPEC is not None and SPEC.loader is not None
NORMALIZER = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(NORMALIZER)


def source_jar(path: Path, newline: bytes, builder: bytes, class_bytes: bytes) -> None:
    entries = {
        "zingg/common/client/ZFrame.class": class_bytes,
        "email.properties": b"host=example.invalid" + newline,
        "jdbc.properties": b"url=jdbc:example" + newline,
        "META-INF/MANIFEST.MF": newline.join(
            (b"Manifest-Version: 1.0", b"Built-By: " + builder, b"Created-By: Apache Maven", b"")),
        "META-INF/maven/zingg/zingg-common-client/pom.properties":
            newline.join((b"#Generated by Maven", b"#Sun Sep 27 00:00:00 UTC 2026", b"version=0.7.0", b"")),
        "META-INF/maven/zingg/zingg-common-client/pom.xml": b"<project>" + newline + b"</project>" + newline,
    }
    with zipfile.ZipFile(path, "w") as archive:
        for name, content in entries.items():
            archive.writestr(name, content)


class CanonicalCapsuleTest(unittest.TestCase):
    def test_platform_newlines_and_builder_do_not_change_canonical_jar(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            windows, linux = root / "windows.jar", root / "linux.jar"
            source_jar(windows, b"\r\n", b"angel.alvarez", b"same-class")
            source_jar(linux, b"\n", b"angelalvarez", b"same-class")
            normalized_windows, normalized_linux = root / "windows-normalized.jar", root / "linux-normalized.jar"
            NORMALIZER.normalize(windows, normalized_windows)
            NORMALIZER.normalize(linux, normalized_linux)
            self.assertEqual(hashlib.sha256(normalized_windows.read_bytes()).digest(),
                             hashlib.sha256(normalized_linux.read_bytes()).digest())
            with zipfile.ZipFile(normalized_windows) as archive:
                self.assertEqual(archive.read("zingg/common/client/ZFrame.class"), b"same-class")
                self.assertNotIn(b"Built-By:", archive.read("META-INF/MANIFEST.MF"))
                self.assertEqual(archive.read("email.properties"), b"host=example.invalid\n")

    def test_actual_class_drift_remains_visible(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            first, second = root / "first.jar", root / "second.jar"
            source_jar(first, b"\r\n", b"windows", b"class-A")
            source_jar(second, b"\n", b"linux", b"class-B")
            canonical_first, canonical_second = root / "first-canonical.jar", root / "second-canonical.jar"
            NORMALIZER.normalize(first, canonical_first)
            NORMALIZER.normalize(second, canonical_second)
            self.assertNotEqual(hashlib.sha256(canonical_first.read_bytes()).digest(),
                                hashlib.sha256(canonical_second.read_bytes()).digest())


if __name__ == "__main__":
    unittest.main()
