package io.zingg.duckdb.compat;
import io.zingg.duckdb.api.DuckException; import io.zingg.duckdb.model.*; import java.nio.charset.StandardCharsets; import java.util.*; import java.util.function.Supplier; import java.util.regex.*;
public final class ModelScorerRegistry {
 private final Map<String,Supplier<ModelScorer>> scorers=new HashMap<>();
 public ModelScorerRegistry(){register("linear",()->new LinearClassifier(List.of("score"),new double[]{1d},0d,true));register("threshold",()->new ClassifierScorer(0.5d));}
 public void register(String type,Supplier<ModelScorer> scorer){if(type==null||!type.matches("[a-z][a-z0-9_-]*"))throw new IllegalArgumentException("invalid scorer type");if(scorers.putIfAbsent(type,Objects.requireNonNull(scorer))!=null)throw new DuckException("scorer already registered: "+type);}
 public ModelScorer create(String type){var factory=scorers.get(type);if(factory==null)throw new DuckException("unsupported scorer type: "+type);return factory.get();}
 public ModelScorer create(ModelReader.LoadedModel model){if(model==null)throw new DuckException("model is required");if(!ModelType.CLASSIFIER.name().equals(model.manifest().modelType()))throw new DuckException("model is not a classifier");String json=new String(model.payload(),StandardCharsets.UTF_8);String kind=field(json,"kind");if(!"linear-classifier".equals(kind))throw new DuckException("unsupported native classifier payload: "+kind);List<String> features=array(json,"features");if(!model.manifest().features().isEmpty()&&!model.manifest().features().equals(features))throw new DuckException("classifier manifest/payload features differ");double[] weights=numbers(json,"weights");if(features.isEmpty()||features.size()!=weights.length)throw new DuckException("classifier feature/weight dimensions differ");double intercept=number(json,"intercept",0d);double threshold=number(json,"threshold",0.5d);boolean logistic=Boolean.parseBoolean(field(json,"logistic"));List<String> base=array(json,"assemblerInputCols");int degree=(int)number(json,"polynomialDegree",0d);if(!base.isEmpty()&&(degree<1||PolynomialFeatures.expand(new double[base.size()],degree).length!=weights.length))throw new DuckException("classifier polynomial feature dimensions differ");return new LinearClassifier(features,base,degree,weights,intercept,logistic,threshold);}
 private static String field(String j,String n){var m=Pattern.compile("\\\""+Pattern.quote(n)+"\\\"\\s*:\\s*(?:\\\"((?:\\\\.|[^\\\"])*)\\\"|([^,}]+))").matcher(j);if(!m.find())return "";return (m.group(1)!=null?m.group(1):m.group(2)).trim().replace("\\\\\"","\"");}
 private static double number(String j,String n,double d){try{return Double.parseDouble(field(j,n));}catch(Exception e){return d;}}
 private static List<String> array(String j,String n){var m=Pattern.compile("\\\""+Pattern.quote(n)+"\\\"\\s*:\\s*\\[([^]]*)\\]").matcher(j);if(!m.find())return List.of();var out=new ArrayList<String>();var i=Pattern.compile("\\\"((?:\\\\.|[^\\\"])*)\\\"").matcher(m.group(1));while(i.find())out.add(i.group(1).replace("\\\\\"","\""));return out;}
 private static double[] numbers(String j,String n){var m=Pattern.compile("\\\""+Pattern.quote(n)+"\\\"\\s*:\\s*\\[([^]]*)\\]").matcher(j);if(!m.find()||m.group(1).isBlank())return new double[0];String[] p=m.group(1).split(",");double[] out=new double[p.length];try{for(int i=0;i<p.length;i++)out[i]=Double.parseDouble(p[i].trim());return out;}catch(NumberFormatException e){throw new DuckException("invalid classifier weights",e);}}
 public Set<String> types(){return Collections.unmodifiableSet(scorers.keySet());}
}
