package io.zingg.duckdb.compat;
import java.util.*;
import java.math.BigInteger;
/** Spark PolynomialExpansion-compatible monomial ordering for degrees 1..N. */
public final class PolynomialFeatures {
  private PolynomialFeatures() {}
 public static double[] expand(double[] values,int degree){if(values==null||values.length==0||degree<1||degree>8)throw new IllegalArgumentException("invalid polynomial input");List<Double> out=new ArrayList<>();for(int max=0;max<values.length;max++)for(int power=1;power<=degree;power++)addValues(values,max-1,degree-power,power,1d,values[max],out);return out.stream().mapToDouble(Double::doubleValue).toArray();}
 public static int featureCount(int inputCount,int degree,int maximum){if(inputCount<1||degree<1||degree>8||maximum<0)throw new IllegalArgumentException("invalid polynomial dimensions");BigInteger combinations=BigInteger.ONE;for(int i=1;i<=degree;i++){combinations=combinations.multiply(BigInteger.valueOf((long)inputCount+i)).divide(BigInteger.valueOf(i));if(combinations.subtract(BigInteger.ONE).compareTo(BigInteger.valueOf(maximum))>0)throw new IllegalArgumentException("polynomial feature dimensions exceed configured limit");}return combinations.subtract(BigInteger.ONE).intValueExact();}
 public static List<String> sqlTerms(List<String> columns,int degree){if(columns==null||columns.isEmpty()||degree<1||degree>8)throw new IllegalArgumentException("invalid polynomial columns");List<String> out=new ArrayList<>();for(int max=0;max<columns.size();max++)for(int power=1;power<=degree;power++)addSql(columns,max-1,degree-power,power,new ArrayList<>(),columns.get(max),out);return out;}
 private static void addValues(double[] v,int index,int remaining,int power,double product,double maxValue,List<Double> out){if(index<0){out.add(product*Math.pow(maxValue,power));return;}for(int exponent=0;exponent<=remaining;exponent++)addValues(v,index-1,remaining-exponent,power,product*Math.pow(v[index],exponent),maxValue,out);}
 private static void addSql(List<String> c,int index,int remaining,int power,List<Integer> exponents,String maxColumn,List<String> out){if(index<0){StringJoiner j=new StringJoiner(" * ","(",")");for(int i=0;i<exponents.size();i++)for(int e=0;e<exponents.get(i);e++)j.add("COALESCE(\""+c.get(i).replace("\"","\"\"")+"\", 0)");for(int i=0;i<power;i++)j.add("COALESCE(\""+maxColumn.replace("\"","\"\"")+"\", 0)");out.add(j.toString());return;}for(int exponent=0;exponent<=remaining;exponent++){exponents.add(exponent);addSql(c,index-1,remaining-exponent,power,exponents,maxColumn,out);exponents.remove(exponents.size()-1);}}
}
