"""Normalize the upstream common/client JAR without installing it in Maven's cache."""
from __future__ import annotations

import re
import hashlib
import json
import sys
import zipfile
from pathlib import Path

TIMESTAMP = (1980, 1, 1, 0, 0, 2)
UPSTREAM_COMMIT = "48cb157b4f35fcfa733e2e7f9699ea988e018738"
PINNED_SHA256 = "a289903fae2ed9ff3a0a3360fed3c80232d70fce848df27e2c6a6ee8406c4b5d"


def canonical_content(name: str, data: bytes) -> bytes:
    if name in {"email.properties", "jdbc.properties", "META-INF/MANIFEST.MF"} or (
        name.startswith("META-INF/maven/") and name.endswith(("/pom.properties", "/pom.xml"))
    ):
        data = data.replace(b"\r\n", b"\n")
    if name == "META-INF/MANIFEST.MF":
        data = re.sub(rb"(?m)^Built-By: [^\n]*\n", b"", data)
    if name.startswith("META-INF/maven/") and name.endswith("/pom.properties"):
        data = re.sub(rb"(?m)^#Generated by Maven\n#.*\n", b"#Generated by Maven\n", data)
    return data


def normalize(source: Path, target: Path) -> None:
    if source.resolve() == target.resolve():
        raise ValueError("source and target JAR must differ")
    target.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(source, "r") as reader, zipfile.ZipFile(target, "w") as writer:
        for old in sorted(reader.infolist(), key=lambda entry: entry.filename):
            info = zipfile.ZipInfo(old.filename, TIMESTAMP)
            info.create_system = 0
            info.external_attr = 0
            info.compress_type = zipfile.ZIP_STORED if old.is_dir() else zipfile.ZIP_DEFLATED
            data = b"" if old.is_dir() else reader.read(old)
            data = canonical_content(old.filename, data)
            writer.writestr(info, data, compress_type=info.compress_type, compresslevel=6)


def main() -> None:
    if len(sys.argv) != 4:
        raise SystemExit("usage: normalize-zingg07-jar.py <source.jar> <normalized.jar> <manifest.json>")
    source, target, manifest = map(Path, sys.argv[1:])
    normalize(source, target)
    source_hash = hashlib.sha256(source.read_bytes()).hexdigest()
    target_hash = hashlib.sha256(target.read_bytes()).hexdigest()
    manifest.parent.mkdir(parents=True, exist_ok=True)
    manifest.write_text(json.dumps({"upstreamCommit": UPSTREAM_COMMIT,
                                    "sourceArchiveSha256": source_hash,
                                    "artifactSha256": target_hash,
                                    "pinnedHashMatched": target_hash == PINNED_SHA256,
                                    "normalization": "sorted-zip-fixed-time-lf-resources-no-builder",
                                    "releaseReady": False}, indent=2) + "\n", encoding="utf-8")
    if target_hash != PINNED_SHA256:
        raise SystemExit(f"candidate capsule differs from pinned SHA-256: {target_hash}")
    print(f"ZINGG07_CAPSULE_SUCCESS sha256={target_hash}")


if __name__ == "__main__":
    main()
